# Site settings
title: Ludovic Henry
author: Ludovic Henry
email: hi@ludovic.dev
# description: >-
url: "https://blog.ludovic.dev"
github_username: "luhenry"
linkedin_username: "ludovic-dev"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - about.md
